# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Projects/Lop

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Projects/Lop

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Projects/Lop/CMakeFiles /mnt/c/Projects/Lop/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Projects/Lop/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ccloxx

# Build rule for target.
ccloxx: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ccloxx
.PHONY : ccloxx

# fast build rule for target.
ccloxx/fast:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/build
.PHONY : ccloxx/fast

src/ast_printer.o: src/ast_printer.cpp.o

.PHONY : src/ast_printer.o

# target to build an object file
src/ast_printer.cpp.o:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/ast_printer.cpp.o
.PHONY : src/ast_printer.cpp.o

src/ast_printer.i: src/ast_printer.cpp.i

.PHONY : src/ast_printer.i

# target to preprocess a source file
src/ast_printer.cpp.i:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/ast_printer.cpp.i
.PHONY : src/ast_printer.cpp.i

src/ast_printer.s: src/ast_printer.cpp.s

.PHONY : src/ast_printer.s

# target to generate assembly for a file
src/ast_printer.cpp.s:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/ast_printer.cpp.s
.PHONY : src/ast_printer.cpp.s

src/error_handler.o: src/error_handler.cpp.o

.PHONY : src/error_handler.o

# target to build an object file
src/error_handler.cpp.o:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/error_handler.cpp.o
.PHONY : src/error_handler.cpp.o

src/error_handler.i: src/error_handler.cpp.i

.PHONY : src/error_handler.i

# target to preprocess a source file
src/error_handler.cpp.i:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/error_handler.cpp.i
.PHONY : src/error_handler.cpp.i

src/error_handler.s: src/error_handler.cpp.s

.PHONY : src/error_handler.s

# target to generate assembly for a file
src/error_handler.cpp.s:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/error_handler.cpp.s
.PHONY : src/error_handler.cpp.s

src/interpreter.o: src/interpreter.cpp.o

.PHONY : src/interpreter.o

# target to build an object file
src/interpreter.cpp.o:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/interpreter.cpp.o
.PHONY : src/interpreter.cpp.o

src/interpreter.i: src/interpreter.cpp.i

.PHONY : src/interpreter.i

# target to preprocess a source file
src/interpreter.cpp.i:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/interpreter.cpp.i
.PHONY : src/interpreter.cpp.i

src/interpreter.s: src/interpreter.cpp.s

.PHONY : src/interpreter.s

# target to generate assembly for a file
src/interpreter.cpp.s:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/interpreter.cpp.s
.PHONY : src/interpreter.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/parser.o: src/parser.cpp.o

.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i

.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s

.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/scanner.o: src/scanner.cpp.o

.PHONY : src/scanner.o

# target to build an object file
src/scanner.cpp.o:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/scanner.cpp.o
.PHONY : src/scanner.cpp.o

src/scanner.i: src/scanner.cpp.i

.PHONY : src/scanner.i

# target to preprocess a source file
src/scanner.cpp.i:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/scanner.cpp.i
.PHONY : src/scanner.cpp.i

src/scanner.s: src/scanner.cpp.s

.PHONY : src/scanner.s

# target to generate assembly for a file
src/scanner.cpp.s:
	$(MAKE) -f CMakeFiles/ccloxx.dir/build.make CMakeFiles/ccloxx.dir/src/scanner.cpp.s
.PHONY : src/scanner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ccloxx"
	@echo "... src/ast_printer.o"
	@echo "... src/ast_printer.i"
	@echo "... src/ast_printer.s"
	@echo "... src/error_handler.o"
	@echo "... src/error_handler.i"
	@echo "... src/error_handler.s"
	@echo "... src/interpreter.o"
	@echo "... src/interpreter.i"
	@echo "... src/interpreter.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/scanner.o"
	@echo "... src/scanner.i"
	@echo "... src/scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

